--------------------------------------------------------
--  DDL for Trigger BI_PERMISSION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SIAMI"."BI_PERMISSION" 
BEFORE INSERT ON PERMISSION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PERMISSION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
ALTER TRIGGER "SIAMI"."BI_PERMISSION" ENABLE
