--------------------------------------------------------
--  DDL for Trigger BI_STATUS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SIAMI"."BI_STATUS" 
BEFORE INSERT ON STATUS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT STATUS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
ALTER TRIGGER "SIAMI"."BI_STATUS" ENABLE
