--------------------------------------------------------
--  Ref Constraints for Table CHECKLIST
--------------------------------------------------------

  ALTER TABLE "SIAMI"."CHECKLIST" ADD CONSTRAINT "CHECKLIST_AMI_ID_FK1" FOREIGN KEY ("ID")
	  REFERENCES "SIAMI"."AMI" ("ID") ENABLE
  ALTER TABLE "SIAMI"."CHECKLIST" ADD CONSTRAINT "CHECKLIST_AUDITEE_ID_FK3" FOREIGN KEY ("AUDITEE_ID")
	  REFERENCES "SIAMI"."AUDITEE" ("USER_ID") ENABLE
  ALTER TABLE "SIAMI"."CHECKLIST" ADD CONSTRAINT "CHECKLIST_STATUS_ID_FK2" FOREIGN KEY ("ID")
	  REFERENCES "SIAMI"."STATUS" ("ID") ENABLE
