--------------------------------------------------------
--  File created - Friday-March-11-2022   
--------------------------------------------------------
@C:\xampp\htdocs\projects\siami6\admin\sql\AMI_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AREA_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITEE_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITOR_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\CHECKLIST_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\KRITERIA_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\PERMISSION_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\ROLE_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\SPM_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\STANDAR_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\STATUS_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\USERS_SEQ.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AMI.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AREA.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITEE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITOR.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\CHECKLIST.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\KRITERIA.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\PERMISSION.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\ROLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\SPM.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\STANDAR.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\STATUS.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\USERS.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AMI_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AREA_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITEE_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITOR_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\CHECKLIST_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\KRITERIA_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\PERMISSION_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\ROLE_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\SPM_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\STANDAR_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\STATUS_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\USERS_DATA_TABLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_AMI.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_AREA.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_AUDITEE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_AUDITOR.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_DEMO_USERS.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_KRITERIA.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_PERMISSION.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_ROLE.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_SPM.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_STANDAR.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_STATUS.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\BI_USERS.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\DUAL.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AMI_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AREA_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITEE_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITOR_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\CHECKLIST_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\KRITERIA_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\PERMISSION_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\ROLE_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\SPM_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\STANDAR_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\STATUS_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\USERS_CONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AMI_REFCONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITEE_REFCONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\AUDITOR_REFCONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\CHECKLIST_REFCONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\KRITERIA_REFCONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\SPM_REFCONSTRAINT.sql
@C:\xampp\htdocs\projects\siami6\admin\sql\USERS_REFCONSTRAINT.sql
