--------------------------------------------------------
--  DDL for Table KRITERIA
--------------------------------------------------------

  CREATE TABLE "SIAMI"."KRITERIA" 
   (	"ID" VARCHAR2(20 BYTE), 
	"STANDAR_ID" NUMBER, 
	"KODE" VARCHAR2(20 BYTE), 
	"KRITERIA" VARCHAR2(225 BYTE), 
	"KET_NILAI" VARCHAR2(225 BYTE), 
	"CATATAN" VARCHAR2(225 BYTE), 
	"CREATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP
   )
